export const CHALLENGE_NAME = { NEW_PASSWORD_REQUIRED: "NEW_PASSWORD_REQUIRED", PASSWORD_VERIFIER:"PASSWORD_VERIFIER" }

export const API_URL = 'https://api.itsag1t5.com/'

export const CARD_POINTS = "CARD_POINTS"
export const TRANSACTION_POINTS = "TRANSACTION_POINTS"